name: Build macOS App

on:
  push:
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Fix package-lock.json
        run: |
          rm -f package-lock.json
          npm install --package-lock-only
          
      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Get version from tag or package.json
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION=$(node -p "require('./package.json').version")
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Build Tauri app (Universal Binary)
        run: |
          npm run tauri build -- --target universal-apple-darwin --bundles dmg,app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: DevMate-v${{ steps.get_version.outputs.version }}-macOS-Installer.dmg
          path: src-tauri/target/universal-apple-darwin/release/bundle/dmg/*.dmg
          if-no-files-found: error

      - name: Create .app ZIP archive
        run: |
          cd src-tauri/target/universal-apple-darwin/release/bundle/macos
          for app in *.app; do
            if [ -d "$app" ]; then
              zip -r "../DevMate-v${{ steps.get_version.outputs.version }}-macOS-Universal.zip" "$app"
              echo "Created ZIP: DevMate-v${{ steps.get_version.outputs.version }}-macOS-Universal.zip"
            fi
          done

      - name: Upload macOS App Bundle (ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: DevMate-v${{ steps.get_version.outputs.version }}-macOS-App-Universal.zip
          path: src-tauri/target/universal-apple-darwin/release/bundle/*.zip
          if-no-files-found: error

      - name: Upload macOS App Bundle (Raw)
        uses: actions/upload-artifact@v4
        with:
          name: DevMate-v${{ steps.get_version.outputs.version }}-macOS-App-Bundle.app
          path: src-tauri/target/universal-apple-darwin/release/bundle/macos/*.app
          if-no-files-found: warn

      - name: Rename files with version for release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          # Create a release directory
          mkdir -p release-assets
          
          # Copy and rename DMG files
          for file in src-tauri/target/universal-apple-darwin/release/bundle/dmg/*.dmg; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              new_name="DevMate-v${{ steps.get_version.outputs.version }}-macOS-Installer.dmg"
              cp "$file" "release-assets/$new_name"
              echo "Renamed $filename to $new_name"
            fi
          done
          
          # Copy and rename ZIP files
          for file in src-tauri/target/universal-apple-darwin/release/bundle/*.zip; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              new_name="DevMate-v${{ steps.get_version.outputs.version }}-macOS-Universal.zip"
              cp "$file" "release-assets/$new_name"
              echo "Renamed $filename to $new_name"
            fi
          done
          
          # List the files that will be uploaded
          echo "Files ready for release:"
          ls -la release-assets/

      - name: Create Release (on tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-assets/*
          generate_release_notes: true
          draft: false
          prerelease: false